trees:
  - tree: files
    path: /unnormalized
    args:
      directory: files/
      subdirectory_handler: heald_labview:subdirectory_handler
  - tree: files
    path: /normalized
    args:
      directory: files/
      subdirectory_handler: heald_labview:normalized_subdirectory_handler